# Generated by Django 4.0.2 on 2022-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='project/')),
                ('description', models.TextField(max_length=100, null=True)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
